---
- name: Converge
  hosts: all
  tasks:
    - name: Load Configuration
      include_vars:
        file: "{{ lookup('env', 'PWD') }}/config.yml"
    - name: Include vault_install
      include_role:
        name: "vault_install"
